[package]
name = "aoc2025"
version = "0.1.0"
edition = "2024"

[dependencies]

[profile.release]
opt-level = 3
lto = "fat"

[[bin]]
path = "src/day_01.rs"
name = "day_01"


[[bin]]
path = "src/day_02.rs"
name = "day_02"
